library_management/library/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('', views.home_view.as_view(), name='home'),
    path('signup/', views.UserSignupView.as_view(), name='signup'),
    path('validate_username/', views.ValidateUsername.as_view(), name='validate_username'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('userprofile/<int:id>/', views.UserProfileView.as_view(), name='userprofile'),
    path('adminprofile', views.AdminProfileView.as_view(), name='adminprofile'),

    path('studentlist/', views.StudentListView.as_view(), name='studentlist'),
    path('studentdetail/<int:id>/', views.StudentDetailView.as_view(), name='studentdetail'),
    path('userdelete/<int:id>/', views.UserDeleteView.as_view(), name='userdelete'),

    path('facultylist/', views.FacultyListView.as_view(), name='facultylist'),
    path('facultydetail/<int:id>/', views.FacultyDetailView.as_view(), name='facultydetail'),

    path('librarianlist/', views.LibrarianListView.as_view(), name='librarianlist'),
    path('librariandetail/<int:id>/', views.LibrarianDetailView.as_view(), name='librariandetail'),

    path('autocompletesearch/', views.AutoCompleteView.as_view(), name='autocompletesearch'),
    path('searchbox/', csrf_exempt(views.SearchBox.as_view()), name='searchbox'),
    path('copies_of_books/', views.CopiesOfBooks.as_view(), name='copies_of_books'),
    path('booklist', views.BookListView.as_view(), name='booklist'),
    path('bookdetail/<int:id>', views.BookDetailView.as_view(), name='bookdetail'),
    path('bookadd/', views.BookAddView.as_view(), name='bookadd'),
    path('bookupdate/<int:id>', views.BookUpdateView.as_view(), name='bookupdate'),
    path('bookdelete/<int:id>', views.BookDeleteView.as_view(), name='bookdelete'),

    path('viewtotalissuedbooks/', views.ViewTotalIssuedBooks.as_view(), name='viewtotalissuedbooks'),
    path('bookrecord/<int:id>/', views.BookIssueView.as_view(), name='bookrecord'),
    path('bookreturn/<int:id>/', views.BookReturnView.as_view(), name='bookreturn'),
]

library_management/library_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('library.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_management/library/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
import datetime
from library.managers import CustomManager


# Create your models here.
class Role(models.Model):
    TYPE = (
        ('Student', 'Student'),
        ('Faculty', 'Faculty'),
        ('Librarian', 'Librarian'),
        ('Admin', 'Admin'),
    )
    role = models.CharField(max_length=255, choices=TYPE, null=True, blank=True)

    def __str__(self):
        return self.role


class Department(models.Model):
    DEPART = (
        ('Computer', 'Computer Engineering'),
        ('Information Technology', 'Information Technology'),
        ('Civil', 'Civil Engineering'),
        ('Electronics & Communication', 'Electronics Engineering'),
        ('Electrical', 'Electrical Engineering'),
        ('Mechanical', 'Mechanical Engineering'),
    )
    department = models.CharField(max_length=255, choices=DEPART, null=True, blank=True)

    def __str__(self):
        return self.department


class User(AbstractUser):
    role = models.ForeignKey(Role, on_delete=models.CASCADE, null=True, blank=True, related_name='myrole')
    address = models.TextField(max_length=255, null=True, blank=True)
    phone_num = PhoneNumberField(null=True, blank=True, unique=True)
    profile_img = models.ImageField(blank=True, upload_to='profile_image/', null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True, related_name='mydepartment')

    # objects = models.Manager()
    # users = CustomManager()


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Faculty(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    CAT = (
        ('History', 'History'),
        ('Technical', 'Technical'),
        ('Educational', 'Educational'),
        ('Biography', 'Biography'),
        ('Cooking', 'Cooking'),
        ('Comics', 'Comics'),
        ('Health', 'Health'),
        ('Travel', 'Travel'),
        ('Horror', 'Horror'),
        ('Mystery', 'Mystery'),
        ('Art & Craft', 'Art & Craft'),
        ('Sports', 'Sports'),
        ('Religion', 'Religion'),
        ('Kids', 'Kids'),
        ('Business', 'Business'),
    )
    category = models.CharField(max_length=255, choices=CAT, blank=True, null= True)

    def __str__(self):
        return self.category


class Book(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, help_text="Select a category for this book", null=True, blank=True, related_name='mycategory')
    book_img = models.ImageField(blank=True, null=True, upload_to='book_image/')
    total_copies_of_books = models.BigIntegerField(default=None, null=True, blank=True)
    available_copies_of_books = models.BigIntegerField(default=None, null=True, blank=True)

    # def __str__(self):
    #     return self.title


class BookRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='myuser')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True, related_name='mybook')
    issue_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    due_date = models.DateTimeField(default=None, null=True, blank=True, editable=False)
    return_date = models.DateTimeField(default=None, null=True, blank=True)

    def Book_due_date(self):
        self.due_date = self.issue_date + datetime.timedelta(days=10)

    def save(self, *args, **kwargs):
        from datetime import datetime, timedelta
        self.due_date = datetime.now() + timedelta(days=10)
        super(BookRecord, self).save(*args, **kwargs)

    def __str__(self):
        return self.book.title

library_management/library/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from library.models import Book, BookRecord, User, Role, Student, Faculty, Librarian, Admin
from library.forms import UserSignupForm, BookForm, BookUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.list import ListView
from django.views import View
from django.contrib import messages, auth
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from library_management.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.http import JsonResponse
from django.db.models import Q
import datetime
from .tasks import sleepy, send_email_task


# Home Page
class home_view(View):
    def get(self, request):
        # to understand the concept of managers
        # return render(request, 'library/index.html', {'user': User.users.get_stu_id_range(3, 6)})
        return render(request, 'library/index.html')


# User SignupForm
class UserSignupView(View):
    def get(self, request):
        return render(request, 'library/signup.html', {'form': UserSignupForm()})

    def post(self, request):
        form = UserSignupForm(request.POST, request.FILES)
        if form.is_valid():
            # subject = 'Welcome to Library Management System'
            # message = 'Thank you for registration in Library Management System!!!'
            # recepient = str(form['email'].value())
            # send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently=False)
            user = form.save()

            if form.cleaned_data['role'].role == 'Admin':
                Admin.objects.create(user=user)
            elif form.cleaned_data['role'].role == 'Student':
                Student.objects.create(user=user)
            elif form.cleaned_data['role'].role == 'Faculty':
                Faculty.objects.create(user=user)
            elif form.cleaned_data['role'].role == 'Librarian':
                Librarian.objects.create(user=user)
            else:
                return render(request, 'library/userprofile.html', {'user': user})

            # user login
            login(request, user)

            # login for specific user
            if Role == 'Admin':
                return HttpResponseRedirect('/adminprofile')
            else:
                return render(request, 'library/userprofile.html', {'user': user})
        else:
            print(form.errors)
            return render(request, 'library/signup.html', {'form': UserSignupForm()})


# Username validation
class ValidateUsername(View):
    def get(self, request):
        username = request.GET.get('username', None)
        data = {
            'is_taken': User.objects.filter(username=username).exists()
        }
        return JsonResponse(data)


# User LoginForm
class LoginView(View):
    def get(self, request):
        return render(request, 'library/login.html', {'form': AuthenticationForm()})

    def post(self, request):
        uname = request.POST.get('username')
        upass = request.POST.get('password')
        user = auth.authenticate(request, username=uname, password=upass)
        if user is not None:
            auth.login(request, user)
            if user.role.role == 'Admin':
                return HttpResponseRedirect('/adminprofile')
            else:
                return render(request, 'library/userprofile.html', {'user': user})
        else:
            messages.info(request, 'Invalid username or password', extra_tags='alert')
            messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))


# User LogOut
class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/login')


# User Profile View
class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = User.objects.get(id=id)
        return render(request, 'library/userprofile.html', {"user": user})


# Admin Profile View
class AdminProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'library/adminprofile.html')


# View will return bookrecords
class ViewTotalIssuedBooks(LoginRequiredMixin, View):
    def get(self, request):
        user = User.objects.get(username=request.user)
        book_records = BookRecord.objects.filter(user=user)
        return render(request, 'library/issuedbooks.html', {'book_records': book_records})


# Class for issue book from library
class BookIssueView(LoginRequiredMixin, View):
    def post(self, request, id):
        flag = 0
        books = Book.objects.get(id=id)
        all_book_records = BookRecord.objects.filter(book__title__iexact=books.title)
        for current_user in all_book_records:
            if current_user.user == request.user and current_user.return_date is None:
                flag = 1
                messages.error(request, "Book Already Issued")
                return HttpResponseRedirect('/booklist')

        if flag == 0:
            all_user_records = BookRecord.objects.filter(Q(user__username__iexact=str(request.user)) & Q(return_date=None)).count()
            if all_user_records > 2:
                messages.error(request, "You cannot issue more than 3 books")
                return HttpResponseRedirect('/booklist')
            elif books.available_copies_of_books == 0:
                messages.error(request, 'This book is out of stock!!')
                return HttpResponseRedirect('/booklist')
            elif books.available_copies_of_books > 0:
                books.available_copies_of_books -= 1
                books.save()
                issue_book_record = BookRecord.objects.create(user=request.user, book=books)
                issue_book_record.save()
                messages.info(request, 'Book issue successfully!!')
            return HttpResponseRedirect('/viewtotalissuedbooks')


# Class for return book to library
class BookReturnView(LoginRequiredMixin, View):
    def post(self, request, id):
        present_book = BookRecord.objects.get(id=id)
        if present_book:
            present_book.return_date = datetime.datetime.now()
            present_book.save()
            books = Book.objects.get(title=present_book.book.title)
            books.available_copies_of_books += 1
            books.save()
            messages.info(request, 'Book return successfully!!')
        else:
            messages.error(request, 'There is no books available!!')
        return HttpResponseRedirect('/booklist')


# Title search
class SearchBox(LoginRequiredMixin, View):
    def post(self, request):
        search_str = request.POST.get('searchText')
        books = Book.objects.filter(title__icontains=search_str)
        context = []
        for book in books:
            details = {
                'id': book.id,
                'title': book.title,
                'author': book.author,
                'category': book.category.category,
                'book_img': book.book_img.url,
                'total_copies_of_books': book.total_copies_of_books,
                'available_copies_of_books': book.available_copies_of_books
            }
            context.append(details)
        return JsonResponse(context, safe=False)


# Autocomplete view for search any book
class AutoCompleteView(LoginRequiredMixin, View):
    def get(self, request):
        if 'term' in request.GET:
            book_records = BookRecord.objects.filter(book__title__icontains=request.GET.get('term'))
            titles = list()

            for books in book_records:
                titles.append(books.book.title) 
            return JsonResponse(titles, safe=False)


# Student List View in admin dashboard
class StudentListView(LoginRequiredMixin, View):
    def get(self, request):
        role = Role.objects.get(role='Student')
        students = User.objects.filter(role=role)
        return render(request, 'library/studentlist.html', {'students': students})


# Student Details View in admin dashboard
class StudentDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        try:
            student = User.objects.get(id=id)
        except User.DoesNotExist:
            return HttpResponseRedirect('/studentlist')
        return render(request, 'library/studentdetail.html', {'student': student})


# User delete View in admin dashboard
class UserDeleteView(LoginRequiredMixin, View):
    def post(self, request, id):
        user = User.objects.get(id=id)
        new_role = user.role.role
        user.delete()

        if new_role == 'Student':
            return HttpResponseRedirect('/studentlist')
        elif new_role == 'Faculty':
            return HttpResponseRedirect('/facultylist')
        else:
            return HttpResponseRedirect('/librarianlist')


# Faculty list View in admin dashboard
class FacultyListView(LoginRequiredMixin, View):
    def get(self, request):
        role = Role.objects.get(role='Faculty')
        faculties = User.objects.filter(role=role)
        return render(request, 'library/facultylist.html', {'faculties': faculties})


# Faculty details View in admin dashboard
class FacultyDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        try:
            faculty = User.objects.get(id=id)
        except User.DoesNotExist:
            return HttpResponseRedirect('/facultylist')
        return render(request, 'library/facultydetail.html', {'faculty': faculty})


# Librarian list View in admin dashboard
class LibrarianListView(LoginRequiredMixin, View):
    def get(self, request):
        role = Role.objects.get(role='Librarian')
        librarians = User.objects.filter(role=role)
        return render(request, 'library/librarianlist.html', {'librarians': librarians})


# Librarian details View in admin dashboard
class LibrarianDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        try:

library_management/templates/library/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>User Register</title>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link href="https://fonts.googleapis.com/css2?family=Potta+One&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book-half" viewBox="0 0 16 16">
            <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
          </svg>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/app.css' %}"
        {% block stylesheet %}{% endblock %}
    </head>
    <body>
        {% block body %}
        <div class="bs-example">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
            <div class="container">
            <a href="/" class="navbar-brand">Library Management</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="/" class="nav-item nav-link active">Home</a>
                        <div class="nav-item dropdown">
                          <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">User</a>
                          <div class="dropdown-menu">
                            <a href="{% url 'signup' %}" class="dropdown-item">Faculty</a>
                            <a href="{% url 'signup' %}" class="dropdown-item">Student</a>
                            <a href="{% url 'signup' %}" class="dropdown-item">Librarian</a>
                            <a href="{% url 'login' %}" class="dropdown-item">Admin</a>
                          </div>
                        </div>
                <div class="collapse navbar-collapse" id="mainMenu">
                    {% if user.is_authenticated %}
                      <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                          </a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                {% if user.is_superuser %}
                                    <a class="dropdown-item" href="{% url 'adminprofile' %}">Profile</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                {% endif %}
                                {% if user.role.role == 'Student' %}
                                    <a class="dropdown-item" href="{% url 'userprofile' user.id %}">Profile</a>
                                    <a class="dropdown-item" href="{% url 'booklist' %}">Issue New Book</a>
                                    <a class="dropdown-item" href="{% url 'viewtotalissuedbooks' %}">View Issued books</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                {% endif %}
                                {% if user.role.role == 'Faculty' %}
                                    <a class="dropdown-item" href="{% url 'userprofile' user.id %}">Profile</a>
                                    <a class="dropdown-item" href="{% url 'booklist' %}">Issue New Book</a>
                                    <a class="dropdown-item" href="{% url 'viewtotalissuedbooks' %}">View Issued books</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                {% endif %}
                                {% if user.role.role == 'Librarian' %}
                                    <a class="dropdown-item" href="{% url 'userprofile' user.id %}">Profile</a>
                                    <a class="dropdown-item" href="{% url 'booklist' %}">Issue New Book</a>
                                    <a class="dropdown-item" href="{% url 'viewtotalissuedbooks' %}">View Issued books</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                {% endif %}
                            </div>
                        </li>
                      </ul>
                      {% else %}
                        <form class="navbar-nav ">
                            <a href="{% url 'login' %}" class="btn btn-primary ml-2">Log in</a>
                            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
                        </form>
                    {% endif %}
                </div>
            </div>
            </div>
        </div>
        </nav>
        {% block content %}
        {% endblock content %}
         <script>
            function changeStatus(){
                var status = document.getElementById("id_role");
                if(status.value == "3" || status.value == "4"){
                    document.getElementById("id_department").style.visibility="hidden";
                }
                else{
                    document.getElementById("id_department").style.visibility="visible";
                }
            }
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js" integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>   
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        </div> 
        {% endblock body %}
        {% block javascript %}{% endblock %}
    </body>
</html>

library_management/templates/library/bookadd.html
{% extends 'library/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container" style="padding-top: 95px; padding-right: 95px;">
    <div class="col-md-15 offset-md-1 mt-10">
        <div class="jumbotron">
            <h1 class="display-4">Add New Book</h1>
            <p class="lead font-bold">Library Management System</p>
            <hr class="my-4">
            <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
                {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
                {% endfor %}
                </div>
                {% endif %}
                {% csrf_token %}
                {{form.title|as_crispy_field}}
                {{form.author|as_crispy_field}}
                {{form.category|as_crispy_field}}
                {{form.book_img|as_crispy_field}}
                {{form.total_copies_of_books|as_crispy_field}}
                {{form.available_copies_of_books|as_crispy_field}}
                <div class="row">
                    <div class="col-md-8">
                        <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i>
                            Submit</button>
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'booklist' %}" class="btn btn-secondary btn-block btn-lg">
                            <i class="fas fa-stream"></i> Back to list
                        </a>
                    </div>
                <br><br>
            </form>
        </div>
    </div>  
</div>
{% endblock %}

library_management/templates/library/bookdetail.html
{% load static %}<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
  <style media="screen">
  .btn-circle.btn-xl {
    width: 70px;
    height: 70px;
    padding: 10px 16px;
    border-radius: 35px;
    font-size: 24px;
    line-height: 1.33;
  }
  .btn-circle {
    width: 30px;
    height: 30px;
    padding: 6px 0px;
    border-radius: 15px;
    text-align: center;
    font-size: 12px;
    line-height: 1.42857;
  }
  .jumbotron{
    margin-top: 0px;
    margin-bottom: 0px;
    text-align: center;
  }
  .jumbotron h1{
    text-align: center;
  }
  </style>
  </head>
  <body>
    {% include "library/base.html" %}
    <br>
    <br>
    <center><h3 style="margin-bottom: 0px;" class ='alert alert-success'>Welcome to Online library!</h3></center>
    <div class="container img jumbotron" style="margin-top: 12rem;">
    <div class="card mb-4" style="max-width: 1000px; margin-left: 40px; margin-top: 10px;">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{book.book_img.url}}" class="card-img" alt="book image" style="width: 200px; margin-top: 30px;">
          </div>
          <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">Book Detail</h2>
                <h4 class="card-title">Title: {{book.title}}</h4>
                <h4 class="card-title">Author: {{book.author}}</h4>
                <h4 class="card-title">Category: {{book.category}}</h4>
                <h4 class="card-title">Total_copies_of_books:<span id="id_total_copies_of_books">{{book.total_copies_of_books}}</span></h4>
                <button id="decrement" class="btn btn-primary btn-sg">-</button>
                <button id="increment" class="btn btn-primary btn-sg">+</button>
                <h4 class="card-title">Available_copies_of_books:<span id="id_available_copies_of_books">{{book.available_copies_of_books}}</span></h4>
            </div>
          </div>
        </div>
    </div>
    </div>
  </body>
  {% block javascript %}
  <script>
    var template = {
        book_id: {{book.id}},
        csrf_token: '{{csrf_token}}',
    }
  </script>
  <script type="text/javascript" src="{% static 'js/incrementDecrementBook.js' %}"></script> 
  {% endblock %}
</html>

library_management/templates/library/signup.html
{% extends "library/base.html" %}
{% load crispy_forms_tags %}
{% load admin_urls %}
{% load static %}
{% block content %}
<div class="container" style="padding-top: 95px; padding-right: 95px;">
  <div class="col-md-15 offset-md-1 mt-10">
      <div class="jumbotron">
          <h1 class="display-4">User SignUp Form</h1>
          <p class="lead font-bold">Library Management System</p>
          <hr class="my-4">
          <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
              {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                  {% endfor %}
              </ul>
              {% endif %}
              {% csrf_token %}
              {{form.role|as_crispy_field}}
              <!-- <div class="form-group">
                  <label class="control-label col-xs-4"><label for="id_role">Role</label></label>
                  <div class="col-xs-10">
                      <select name="role" id="id_role" onchange="changeStatus()">
                          <option value="" selected="">---------</option>
                          <option value="1">Student</option>
                          <option value="2">Faculty</option>
                          <option value="3">Librarian</option>
                          <option value="3">Admin</option>
                      </select>
                  </div>
              </div> -->
              {{form.username|as_crispy_field}}
              {{form.first_name|as_crispy_field}}
              {{form.last_name|as_crispy_field}}
              {{form.email|as_crispy_field}}
              {{form.password1|as_crispy_field}}
              {{form.password2|as_crispy_field}}
              {{form.address|as_crispy_field}}
              {{form.phone_num|as_crispy_field}}
              {{form.profile_img|as_crispy_field}}
              {{form.department|as_crispy_field}}
              <div class="row">
                  <div class="col-md-12">
                      <button type="submit" class="btn btn-success btn-block btn-lg">SignUp</button>
                  </div>
              </div>
              <br><br>
              <div class="text-center">Already have an account? <a href="/login">Login here</a></div>
          </form>
        </div>
      </div>  
  </div>
  {% block javascript %}
  <script type="text/javascript" src="{% static 'js/userNameValidation.js' %}"></script>
  {% endblock %}
{% endblock content %}